#!/bin/bash

# Exit if any command fails
set -e

# Ensure lein profile passed in
if [[ -z $ENVIRONMENT ]]; then
  echo "Set ENVIRONMENT as the environment you're deploying to"
  exit 1
fi

lein with-profiles $ENVIRONMENT immutant archive

cp target/hermes.ima /servers/hermes/
